
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    DROP TABLE "GroupNotificationPlatforms";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    DROP TABLE "ServiceNotificationGroups";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    DROP TABLE "UserNotificationGroups";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    DROP TABLE "NotificationGroups";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    DROP TABLE "Users";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "UpdatedAt" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "Name" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "MetricName" TYPE character varying(75);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "Description" TYPE character varying(125);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "CreatedBy" TYPE character varying(35);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    ALTER TABLE "MonitoringRules" ADD "LastEvaluated" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911011453_Rules2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250911011453_Rules2', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911025924_Rules3') THEN
    ALTER TABLE "MonitoringRules" DROP COLUMN "RuleType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911025924_Rules3') THEN
    ALTER TABLE "MonitoringRules" ADD "AlertMessage" character varying(250) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911025924_Rules3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250911025924_Rules3', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911100435_Rules4') THEN
    ALTER TABLE "MonitoringRules" DROP COLUMN "Actions";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911100435_Rules4') THEN
    ALTER TABLE "MonitoringRules" ADD "AlertChannels" text[] NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911100435_Rules4') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250911100435_Rules4', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    CREATE TABLE "Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(75) NOT NULL,
        "Password" character varying(150) NOT NULL,
        "PhoneNumber" character varying(15),
        "WorkEmail" character varying(75) NOT NULL,
        "OrganizationId" integer NOT NULL,
        "Role" text NOT NULL,
        "MFASecret" character varying(150) NOT NULL,
        "IsMFAEnabled" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN

                    INSERT INTO "Users" ("Id", "FullName", "Password", "WorkEmail", "OrganizationId", "Role", "MFASecret", "IsMFAEnabled", "DateCreated")
                    VALUES (1, 'System User', 'N/A', 'system@example.com', 1, 'System', 'N/A', false, NOW());
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN

                    UPDATE "MonitoringRules" 
                    SET "CreatedBy" = '1' 
                    WHERE "CreatedBy" IS NULL OR "CreatedBy" = '';
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN

                    ALTER TABLE "MonitoringRules" 
                    ALTER COLUMN "CreatedBy" TYPE bigint 
                    USING "CreatedBy"::bigint;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    ALTER TABLE "MonitoringRules" ADD "RecipientUserIds" text[];
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN

                    UPDATE "MonitoringRules" 
                    SET "RecipientUserIds" = '{}' 
                    WHERE "RecipientUserIds" IS NULL;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    ALTER TABLE "MonitoringRules" ALTER COLUMN "RecipientUserIds" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    CREATE INDEX "IX_MonitoringRules_CreatedBy" ON "MonitoringRules" ("CreatedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    ALTER TABLE "MonitoringRules" ADD CONSTRAINT "FK_MonitoringRules_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911124149_Rule5') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250911124149_Rule5', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911181304_Rule6') THEN
    ALTER TABLE "MonitoringRules" ADD "ServiceId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250911181304_Rule6') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250911181304_Rule6', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913094747_SlaackId') THEN
    ALTER TABLE "Users" ADD "SlackId" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250913094747_SlaackId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250913094747_SlaackId', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250914025225_RemoveUnusedUserFields') THEN
    ALTER TABLE "Users" DROP COLUMN "Password";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250914025225_RemoveUnusedUserFields') THEN
    ALTER TABLE "Users" DROP COLUMN "PhoneNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250914025225_RemoveUnusedUserFields') THEN
    ALTER TABLE "Users" DROP COLUMN "Role";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250914025225_RemoveUnusedUserFields') THEN
    ALTER TABLE "Users" DROP COLUMN "SlackId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250914025225_RemoveUnusedUserFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250914025225_RemoveUnusedUserFields', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250915092229_FD') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250915092229_FD', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917052254_IdKey') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917052254_IdKey', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917052624_ConflictKey') THEN
    ALTER TABLE "RuleConflicts" ADD "Id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917052624_ConflictKey') THEN
    ALTER TABLE "RuleConflicts" ADD CONSTRAINT "PK_RuleConflicts" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917052624_ConflictKey') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917052624_ConflictKey', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917060325_RuleEvaluation') THEN
    CREATE TABLE "RuleEvaluations" (
        "Id" uuid NOT NULL,
        "RuleId" uuid NOT NULL,
        "MetricValue" numeric NOT NULL,
        "ThresholdBreached" boolean NOT NULL,
        "EvaluationTime" timestamp with time zone NOT NULL,
        "EvaluationDuration" interval NOT NULL,
        "AlertFired" boolean NOT NULL,
        CONSTRAINT "PK_RuleEvaluations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RuleEvaluations_MonitoringRules_RuleId" FOREIGN KEY ("RuleId") REFERENCES "MonitoringRules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917060325_RuleEvaluation') THEN
    CREATE INDEX "IX_RuleEvaluations_RuleId" ON "RuleEvaluations" ("RuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917060325_RuleEvaluation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917060325_RuleEvaluation', '9.0.6');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917061840_RuleId') THEN
    ALTER TABLE "RuleEvaluations" ALTER COLUMN "Id" SET DEFAULT (gen_random_uuid());
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917061840_RuleId') THEN
    ALTER TABLE "RuleConflicts" ALTER COLUMN "Description" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917061840_RuleId') THEN
    ALTER TABLE "RuleConflicts" ALTER COLUMN "ConflictType" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917061840_RuleId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917061840_RuleId', '9.0.6');
    END IF;
END $EF$;
